document.addEventListener('DOMContentLoaded', function () {
    const romsSection = document.getElementById('roms-section');
    const roms = [
        'adventure-blue-chapter-b1.1 .gba',
        'adventure-gold-chapter-b1.2 .gba',
        'adventure-green-chapter-b3 .gba',
        'adventure-red-chapter-b15-exp-fix-c .gba',
        'adventure-to-empire-isle-v0.5 .gba',
        'adventure-yellow-chapter-demo-fixed .gba',
        'altered-v1.11.2 .gba',
        'alternate-evolutions-final .gba',
        'aluminum-v0.1 .gba',
        'ancient-ruby-a1.0.gbc',
        'another-emerald-v1.10c .gba',
        'ash-hoenn-2021-06-08 .gba',
        'ash-johto-2021-01-17 .gba',
        'ash-kanto-2020-05-27 .gba',
        'ash-kanto-msb-2021-07-15 .gba',
        'ash-orange-league-2020-08-17 .gba',
        'ashgray-b4.5.3 .gba',
        'blazing-emerald-v1.6 .gba',
        'blue-no-hud.gb',
        'clays-calamity-1-v10 .gba',
        'clays-calamity-2-v5.1 .gba',
        'clays-calamity-3-v3.9.3 .gba',
        'cloud white 2 .gba',
        'cloud-white-2-v279 .gba',
        'cloud-white-3-v277 .gba',
        'cloud-white-v515 .gba',
        'cosmicemerald-2019-12-24 .gba',
        'crystal-team-stealing.gbc',
        'dark-rising-2-completed .gba',
        'dark-rising-order-destroyed-completed .gba',
        'dark-rising-origins-wc-final .gba',
        'darkfire-b2.0.5 .gba',
        'darkrising-1-complete .gba',
        'darkrising-kaizo-2017-04-27 .gba',
        'dbz_supersonic .gba',
        'delta-emerald-v1.1.5 .gba',
        'delta-fusion .gba',
        'digimon_racing .gba',
        'Dragonball - Advanced Adventure # GBA .gba',
        'Dragonball GT - Transformation # GBA .gba',
        'Dragonball Z - Buus Fury # GBA.gba',
        'Dragonball Z - Supersonic Warriors # GBA .gba',
        'Dragonball Z - Taiketsu # GBA .gba',
        'Dragonball Z - the Legacy of Goku # GBA .gba',
        'Dragonball Z - the Legacy of Goku 2 # GBA .gba',
        'dreams-v1.5.1 .gba',
        'Emerald Extreme Rom .gba',
        'emerald-chaos-rush .gba',
        'emerald-genesis-b2.1 .gba',
        'emerald-multiplayer-a0.4.3 .gba',
        'emerald-negative-exp .gba',
        'emerald-randomizer .gba',
        'firered-chaos-rush .gba',
        'fused-dimensions-v1.6 .gba',
        'fusion-3 .gba',
        'fusion-origins-v3.8 .gba',
        'gba_video_pokemon_1 .gba',
        'gba_video_pokemon_2 .gba',
        'gba_video_pokemon_3 .gba',
        'gba_video_pokemon_4 .gba',
        'gen-1-2player.gb',
        'goldensun .gba',
        'Goomba V2.2 - Pokemon Black - Special Palace Edition 1 by MB Hacks (Red Hack) .gba',
        'joels-bizarre-pokeventure.gbc',
        'kirbymirror .gba',
        'kirbynightmare .gba',
        'league-of-legends-2017-09-12 .gba',
        'monopoly .gba',
        'moon-demo .gba',
        'mortal_kombat .gba',
        'mysteryred .gba',
        'pokeland-0-ep-1-v1.1 .gba',
        'pokemal-beta .gba',
        'pokemblem-2021-10-09 .gba',
        'pokemet-v2 .gba',
        'Pokemon - Liquid Crystal (v3.3.00512) .gba',
        'Pokemon A Grand Day Out .gba',
        'Pokemon Adventure - Red Chapter (Beta 15 + Expansion Fix) .gba',
        'Pokemon Altered Emerald (v4.1e) .gba',
        'Pokemon extreme randomizer ver. 2 .gba',
        'Pokemon Ultra Shiny Gold Sigma (Hack v1.3.8) .gba',
        'Pokemon Ultra Violet (1.22) LSA (Fire Red Hack) .gba',
        'pokemonek .gba',
        'pokemonemerald .gba',
        'pokemonflorasky .gba',
        'pokemongb .gba',
        'pokemongreen .gba',
        'pokemonlp .gba',
        'pokemonred .gba',
        'pokemonruby .gba',
        'pokemonsapphire .gba',
        'pokemon_fire_red_randomizer_version_demo .gba',
        'pokes-bizarre-adventure-v1.1-final .gba',
        'pokewb .gba',
        'rowe-v1.5.2 .gba',
        'ruby-destiny-bt-b1 .gba',
        'ruby-destiny-log-2017v1 .gba',
        'ruby-destiny-rol-2016v4.1 .gba',
        'ruby-destiny-rol-remake-b1 .gba',
        'ruby-destiny-rr-hrm-2021-07-08 .gba',
        'ruby-wonder-guard .gba',
        'supermarioadvance .gba',
        'supermarioadvance2 .gba',
        'supermarioadvance3 .gba',
        'supermarioadvance4 .gba',
        'team-training-v8 .gba',
        'Touhou Puppet Play Enhanced (Reloaded v4.6) .gba',
        'Touhou Puppet Play Enhanced v1.11 - Original .gba',
        'Touhou Puppet Play Enhanced v1.11 - Renko .gba',
        'Touhoumon Purple (Difficulty - Hard) .gba',
        'Touhoumon Purple (Difficulty - Ultimate) .gba',
        'Touhoumon Purple (Difficulty - Very Hard) .gba',
        'Touhoumon Purple (Original) .gba',
        'Touhoumon Purple (Sandbox) .gba',
        'turok_evolution .gba',
        'ygo-pokeduel-v3.0 .gba',
        
        
    ];

    function displayROMs(filter = '') {
        romsSection.innerHTML = ''; // Clear current ROMs
        roms.filter(rom => filter === 'ALL' || rom.charAt(0).toUpperCase() === filter)
            .forEach(rom => {
                const romElement = document.createElement('div');
                romElement.classList.add('rom');
                romElement.textContent = rom;
                // Adjust the path to the ROM files as necessary
                romElement.innerHTML = `<a href="ROMS/${rom}" download>${rom}</a>`;
                romsSection.appendChild(romElement);
            });
    }

    window.filterROMs = displayROMs;

    // Initially display all ROMs
    displayROMs('ALL');
});
